-- MOTIVA - Sprint 03
-- Massa inicial coerente com os exemplos e regras da Sprint 02.
-- Execute depois de seu-script-criacao.sql.

WHENEVER SQLERROR EXIT FAILURE ROLLBACK

INSERT INTO TB_EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE, ATIVA)
VALUES ('Equipe Alpha', 'ROCADA MECANIZADA', 'S');

INSERT INTO TB_EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE, ATIVA)
VALUES ('Equipe Beta', 'ROCADA MANUAL', 'S');

INSERT INTO TB_EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE, ATIVA)
VALUES ('Equipe Preventiva', 'PULVERIZACAO PREVENTIVA', 'S');

INSERT INTO TB_TRECHO_RODOVIA (
    QUILOMETRO,
    SENTIDO,
    ALTURA_VEGETACAO_CM,
    TIPO_CRESCIMENTO,
    AREA_SENSIVEL,
    MONITORADO_IOT,
    CODIGO_SENSOR
) VALUES (10, 'Norte', 28.00, 'SECO', 'N', 'N', NULL);

INSERT INTO TB_TRECHO_RODOVIA (
    QUILOMETRO,
    SENTIDO,
    ALTURA_VEGETACAO_CM,
    TIPO_CRESCIMENTO,
    AREA_SENSIVEL,
    MONITORADO_IOT,
    CODIGO_SENSOR
) VALUES (11, 'Norte', 42.00, 'NORMAL', 'N', 'N', NULL);

INSERT INTO TB_TRECHO_RODOVIA (
    QUILOMETRO,
    SENTIDO,
    ALTURA_VEGETACAO_CM,
    TIPO_CRESCIMENTO,
    AREA_SENSIVEL,
    MONITORADO_IOT,
    CODIGO_SENSOR
) VALUES (12, 'Sul', 58.00, 'NORMAL', 'S', 'N', NULL);

INSERT INTO TB_TRECHO_RODOVIA (
    QUILOMETRO,
    SENTIDO,
    ALTURA_VEGETACAO_CM,
    TIPO_CRESCIMENTO,
    AREA_SENSIVEL,
    MONITORADO_IOT,
    CODIGO_SENSOR
) VALUES (13, 'Sul', 68.00, 'UMIDO', 'N', 'N', NULL);

INSERT INTO TB_TRECHO_RODOVIA (
    QUILOMETRO,
    SENTIDO,
    ALTURA_VEGETACAO_CM,
    TIPO_CRESCIMENTO,
    AREA_SENSIVEL,
    MONITORADO_IOT,
    CODIGO_SENSOR
) VALUES (14, 'Leste', 75.00, 'UMIDO', 'S', 'S', 'IOT-014');

INSERT INTO TB_TRECHO_RODOVIA (
    QUILOMETRO,
    SENTIDO,
    ALTURA_VEGETACAO_CM,
    TIPO_CRESCIMENTO,
    AREA_SENSIVEL,
    MONITORADO_IOT,
    CODIGO_SENSOR
) VALUES (15, 'Oeste', 44.00, 'UMIDO', 'N', 'S', 'IOT-015');

INSERT INTO TB_INTERVENCAO_OPERACIONAL (
    ID_TRECHO,
    ID_EQUIPE,
    TIPO_INTERVENCAO,
    NIVEL_PRIORIDADE,
    ALTURA_PROJETADA_CM,
    JUSTIFICATIVA,
    DATA_INTERVENCAO,
    STATUS
)
SELECT
    T.ID_TRECHO,
    E.ID_EQUIPE,
    'PULVERIZACAO',
    'MEDIA',
    42.00,
    'Vegetacao em crescimento inicial. Recomendada pulverizacao preventiva.',
    LOCALTIMESTAMP - INTERVAL '5' DAY,
    'CONCLUIDA'
FROM TB_TRECHO_RODOVIA T
CROSS JOIN TB_EQUIPE_MANUTENCAO E
WHERE T.QUILOMETRO = 11
  AND T.SENTIDO = 'Norte'
  AND E.NOME = 'Equipe Preventiva';

INSERT INTO TB_INTERVENCAO_OPERACIONAL (
    ID_TRECHO,
    ID_EQUIPE,
    TIPO_INTERVENCAO,
    NIVEL_PRIORIDADE,
    ALTURA_PROJETADA_CM,
    JUSTIFICATIVA,
    DATA_INTERVENCAO,
    STATUS
)
SELECT
    T.ID_TRECHO,
    E.ID_EQUIPE,
    'ROCADA_MANUAL',
    'ALTA',
    68.00,
    'Vegetacao acima do limite de atencao. Recomendada rocada manual.',
    LOCALTIMESTAMP - INTERVAL '4' DAY,
    'CONCLUIDA'
FROM TB_TRECHO_RODOVIA T
CROSS JOIN TB_EQUIPE_MANUTENCAO E
WHERE T.QUILOMETRO = 12
  AND T.SENTIDO = 'Sul'
  AND E.NOME = 'Equipe Beta';

INSERT INTO TB_INTERVENCAO_OPERACIONAL (
    ID_TRECHO,
    ID_EQUIPE,
    TIPO_INTERVENCAO,
    NIVEL_PRIORIDADE,
    ALTURA_PROJETADA_CM,
    JUSTIFICATIVA,
    DATA_INTERVENCAO,
    STATUS
)
SELECT
    T.ID_TRECHO,
    E.ID_EQUIPE,
    'ROCADA_MECANIZADA',
    'CRITICA',
    95.20,
    'Vegetacao projetada em nivel critico. Exige rocada mecanizada.',
    LOCALTIMESTAMP - INTERVAL '3' DAY,
    'CONCLUIDA'
FROM TB_TRECHO_RODOVIA T
CROSS JOIN TB_EQUIPE_MANUTENCAO E
WHERE T.QUILOMETRO = 13
  AND T.SENTIDO = 'Sul'
  AND E.NOME = 'Equipe Alpha';

INSERT INTO TB_INTERVENCAO_OPERACIONAL (
    ID_TRECHO,
    ID_EQUIPE,
    TIPO_INTERVENCAO,
    NIVEL_PRIORIDADE,
    ALTURA_PROJETADA_CM,
    JUSTIFICATIVA,
    DATA_INTERVENCAO,
    STATUS
)
SELECT
    T.ID_TRECHO,
    E.ID_EQUIPE,
    'ROCADA_MECANIZADA',
    'CRITICA',
    115.00,
    'Vegetacao projetada em nivel critico. Exige rocada mecanizada.',
    LOCALTIMESTAMP - INTERVAL '2' DAY,
    'PLANEJADA'
FROM TB_TRECHO_RODOVIA T
CROSS JOIN TB_EQUIPE_MANUTENCAO E
WHERE T.QUILOMETRO = 14
  AND T.SENTIDO = 'Leste'
  AND E.NOME = 'Equipe Alpha';

INSERT INTO TB_INTERVENCAO_OPERACIONAL (
    ID_TRECHO,
    ID_EQUIPE,
    TIPO_INTERVENCAO,
    NIVEL_PRIORIDADE,
    ALTURA_PROJETADA_CM,
    JUSTIFICATIVA,
    DATA_INTERVENCAO,
    STATUS
)
SELECT
    T.ID_TRECHO,
    E.ID_EQUIPE,
    'ROCADA_MANUAL',
    'ALTA',
    61.60,
    'Vegetacao acima do limite de atencao. Recomendada rocada manual.',
    LOCALTIMESTAMP - INTERVAL '1' DAY,
    'PLANEJADA'
FROM TB_TRECHO_RODOVIA T
CROSS JOIN TB_EQUIPE_MANUTENCAO E
WHERE T.QUILOMETRO = 15
  AND T.SENTIDO = 'Oeste'
  AND E.NOME = 'Equipe Beta';

INSERT INTO TB_RELATORIO_PRIORIDADE (
    DATA_GERACAO,
    QT_NORMAL,
    QT_BAIXA,
    QT_MEDIA,
    QT_ALTA,
    QT_CRITICA,
    RESUMO
) VALUES (
    LOCALTIMESTAMP,
    1,
    0,
    1,
    2,
    2,
    '6 trechos analisados: 1 normal, 0 baixa, 1 media, 2 alta e 2 critica.'
);

COMMIT;
